# Generated by Django 2.1.7 on 2019-04-13 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190413_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated time'),
        ),
    ]
