# Generated by Django 2.1.7 on 2019-04-17 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='update_time',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created time'),
        ),
    ]
