# Generated by Django 2.1.7 on 2019-04-14 05:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated time')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_cnt', models.IntegerField(default=0)),
                ('visitor_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='visited time')),
                ('visitor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='statistic.Visitor')),
            ],
        ),
    ]
